@startuml "diagramaColaboracion"

skinparam noteBackgroundColor transparent
skinparam noteBorderColor transparent
hide members

object "nombre objeto: Clase" as objeto1
object ": Clase" as objeto2

objeto1 -d--> objeto2
note on link
    1: mensaje()
end note

objeto2 -u-> objeto1
note on link
    2: otroMensaje()
end note

@enduml
