@startuml "diagramaColaboracion"

object ": Actor" as user
object ": EngargadoPedido" as engargadoPedido
object ": BBDDEntradas" as bbdd
object ": OficinaCredito" as oficinaCredito

user -r- engargadoPedido: pedir(pedido, cliente) >

engargadoPedido -r- bbdd: 2: coste = reservar(pedido) >

engargadoPedido -d- oficinaCredito: >  1: comprobarCredito(cliente) \n 3: cargarCuenta(cliente, coste) >

@enduml
