@startuml taller_usecases
left to right direction

actor "Personal Receptor" as Recepcion
actor "Mecánico" as Mecanico
actor "Jefe Taller" as Jefe
actor "Gerente Taller" as Gerente
actor "Administrador" as Admin
actor "Usuario" as Usuario

Gerente -l-|> Admin
Jefe -l-|> Admin
Admin -l-|> Usuario
Recepcion -l-|> Usuario
Mecanico -l-|> Usuario

rectangle "Taller Mecánico" {
  package "Administrar Reportes"
  package "Administrar reparaciones"
  package "Administrar Facturas"
  package "Administrar Empleados"
  package "Administrar Usuarios"
  package "Administrar Seguridad"
}

Recepcion -- "Administrar Reportes"
Mecanico -- "Administrar Reportes"
Mecanico -- "Administrar reparaciones"
Gerente -- "Administrar Facturas"
Gerente -- "Administrar Reportes"
Jefe -- "Administrar Empleados"
Admin -- "Administrar Usuarios"
Usuario -- "Administrar Seguridad"

@enduml