@startuml
skinparam style strictuml
left to right direction
skinparam defaultTextAlignment center
skinparam defaultFontSize 11

actor Mechanic

boundary "Reports\nView" as ReportsView
control "ShowReports\nController" as ShowReportsController
entity Client
entity Vehicle
entity Employee

boundary "EditReport\nView" as EditReportView
control "SetRepairs\nController" as SetRepairsController
entity Report
entity Repair
entity SparePart

Mechanic --> ReportsView
ReportsView --> ShowReportsController
ShowReportsController --> Report

ReportsView --> EditReportView

Mechanic --> EditReportView
EditReportView --> SetRepairsController
SetRepairsController --> Report
Report --> Repair
Report  --> SparePart
Report --> Client
Report --> Vehicle
Report --> Employee

@enduml