@startuml
left to right direction

object ": Mechanic" as Mechanic
object ": Reports\nView" as ReportsView
object ": ShowReports\nController" as ShowReportsController
object ": EditReport\nView" as EditReportView
object ": SetRepairs\nController" as SetRepairsController
object ": Report" as Report
object ": Repair" as Repair
object ": SparePart" as SparePart
object ": Client" as Client
object ": Vehicle" as Vehicle
object ": Employee" as Employee

Mechanic -- ReportsView : > 1: getReports() \n 4: showReport(reportID)
ReportsView -- ShowReportsController : > 2: getReports() \n 5: getReport(reportID)
ShowReportsController -- Report : > 3: getData()

ReportsView -- EditReportView: > 6: showReport(reportData)

Mechanic -- EditReportView : > 7: setRepair(date, time, \nhoursWorked, description) \n 11: setSparePart(sparePartCode)
EditReportView -- SetRepairsController : > 8: setRepair(reportID, repairData) \n 12: setSparePart(reportID, sparePartCode) \n 10: showResult(message) <
SetRepairsController -- Report : > 9: setRepair(repairData) \n 13: setSpareParte(sparePartCode)
Report -- Repair
Report -- SparePart
Report -- Client
Report -- Vehicle
Report -- Employee
@enduml